### ISSUE TITLE
Add the mondrove fungus

### ISSUE THREAD

**Issue by TheOnlyTails** [Team-Cryptic-Cosmos/Cryptic-Cosmos#26]
there will be giant trees in the middle of the forests that you can go inside and find roots of the mondrove tree. 

With these roots you can purify the infected wood blocks and even the mobs themselves!

**Comment by HauntedChest13** [comment]
There will be giant main fungi as structures in the forest which inside and out you can find the mondrove fungus which is a deadly effect that could kill you if you don't have the cure. With these fungi, you could make the potion of corruption which would give the effect but with potions.

**Comment by TheOnlyTails** [comment]
That's in another issue.

**Comment by HauntedChest13** [comment]
which part? the effect and the potions or the structure? or the fungus itself?

**Comment by DemologyWarrior1** [comment]
How will the fungus kill you? Effect or Potion-like effect or just insta-death

**Comment by TheOnlyTails** [comment]
> which part? the effect and the potions or the structure? or the fungus itself?
The effect and potions

**Comment by HauntedChest13** [comment]
ah ok

**Comment by TheOnlyTails** [comment]
> How will the fungus kill you? Effect or Potion-like effect or just insta-death
A lot of instant damage, then poison-like damange (but more powerful).

**Comment by TheOnlyTails** [comment]
Also, it's not a structure, it's a feature (like trees).

**Comment by HauntedChest13** [comment]
It a lot of instant damage and then slowly you get damage by each heart. It won't stop until you cure it with a potion.

**Comment by HauntedChest13** [comment]
> Also, it's not a structure, it's a feature (like trees).

oh ok
