### ISSUE TITLE
Add the potion of purification and corruption

### ISSUE THREAD

**Issue by TheOnlyTails** [Team-Cryptic-Cosmos/Cryptic-Cosmos#27]
The potion of purification will decrease one infection level.
The potion of corruption will increase one infection level.

**Comment by JefftheFifth** [comment]
Could we change the Potion of Corruption's name to "Vial of Corruption"? Imo it sounds way cooler.

**Comment by HauntedChest13** [comment]
Yes! It sounds really cool!

**Comment by xf8b** [comment]
vial of 19 dollar fortnite card
